### ISSUE TITLE
Change order of the list command and add folder/category

### ISSUE THREAD

**Issue by renadmunna** [deepakg202/vscode-save-commands#15]
it will be very helpful if the order of the list command can be changed
to manage and organise adding folders/categories in the list

**Comment by padrickr** [comment]
> it will be very helpful if the order of the list command can be changed to manage and organise adding folders/categories in the list

+1 to this

**Comment by deepakg202** [comment]
Hi, 
It has been more than a year since this issue was created. Finally found some time to work on it. 
The new release #20 adds support for folders and import/export. 

Unfortunately, the ordering of the list via drag/drop seemed a bit complicated at this time handling all the cases between global and workspace states and now folders. Have to spend some more time figuring things. But still custom ordering might still be possible (haven't tested but it should work) by changing the order in the json file which is exported and reimporting it.

Closing this issue for now. 

Thanks
